### ISSUE TITLE
[PlaceholderAPI] failed to load class files of expansions

### ISSUE THREAD

**Issue by a8474** [PikaMug/PlaceholderExpansion-Quests#12]
Spigot Version: paper-1.17.1
Quests Version: 3.9.2
PlaceholderAPI Version: 2.10.10
Expansion-quests.jar Version: 1.4 (also tried with 1.3 and 1.2).
Console Pastebin : https://pastebin.com/1iaxNcE4

Quests Expansion API is not being loaded and is preventing other placeholders from functioning properly.

I have tried: updating pAPI, updating the Expansion jar and downgrading the Expansion jar. I haven't tried to reinstall Quests as the plugin is functional.

Thank you.

**Comment by PikaMug** [comment]
If this is still an issue I would need to see a startup log as the exception implies Quests is not installed or enabled.
