### ISSUE TITLE
[PlaceholderAPI] failed to load class files of expansions 

### ISSUE THREAD

**Issue by budur01** [PikaMug/PlaceholderExpansion-Quests#14]
error : https://pastebin.com/kpg8PbN6
versions: https://imgur.com/L7LwWGX
server versions: airplane 1.17.1
Quests Expansion API is not being loaded and is preventing other placeholders from functioning properly.

for example vault balance's placeholders

**Comment by budur01** [comment]
@PikaMug can u help me

**Comment by PikaMug** [comment]
Wrong Quests plugin. This is for https://github.com/PikaMug/Quests
