### ISSUE TITLE
[Suggestion] Add or modify placeholder.

### ISSUE THREAD

**Issue by EseKriper** [PikaMug/PlaceholderExpansion-Quests#15]
Hi, I have a problem with the expansion.

My suggestion is to add the placeholder _%quests_player_current_quest_names_line%_ or change the _%quests_player_current_quest_names%_ to use a comma, dot or some other symbol as separator, without making line break.

----------------------------------------------------------

I plan to make a special menu with deluxemenus for daily and single quests, for that we must filter the quest names. We get the names with the placeholder _%quests_player_current_quest_names%_ but when we try to use it with more than 1 active quest we have an error:

> [PAPI] [Javascript-Expansion] An error occurred while executing the script 'questsmenu
> javax.script.ScriptException: <eval>:1:30 Missing close quote
> var quest = "Kill with hand 

This is the JS code we use for testing a customplaceholder.
```
var quest = "%quests_player_current_quest_names%";
function questmenu() {
    return quest.split(/\r?\n/).length;
}
questmenu();
```

This happens because a line break is being made when displaying the results of the placeholder.
[Here is my problem in the code.](https://github.com/PikaMug/PlaceholderExpansion-Quests/blob/master/src/main/java/me/pikamug/questsexpansion/QuestsExpansion.java#L188)

**Comment by PikaMug** [comment]
While I understand a line break may not be ideal, why does this necessitate a change to PlaceholderExpansion-Quests? It seems to me that you should just fix how the JS array is getting parsed. Can't tell for sure without seeing the full code.

**Comment by EseKriper** [comment]
The problem is the JS expansion of the placeholder api does not support line breaks, so we cannot work with placeholders that are using line breaks.

I have tried to return the value as I get it from the placeholder but the code broke as soon as it tries to read the placeholder.
- Code:
```
var quest = '%quests_player_cooldown_time_remaining_matar con arco%';
function questmenu() {
    return quest;
}
questmenu();
```
- Error:
https://pastebin.com/F13eJbyN

**Comment by PikaMug** [comment]
I'm still confused. Even if the JavaScript expansion has an issue with line breaks (I don't see why it would), just filter them out before calling your function. Also the `%player_cooldown_time_remaining_%` placeholder doesn't use line breaks, so it seems to me there's something else going on there.

**Comment by EseKriper** [comment]
Oh sorry, I was testing with other placeholders and they worked fine, but only the ones with line breaks I don't get.

The placeholder in the code that is giving me an error is %quests_player_current_quest_names%.

I will try filtering first.
