### ISSUE TITLE
New line bug 

### ISSUE THREAD

**Issue by zetlas1610** [PikaMug/PlaceholderExpansion-Quests#17]
Hey I have a problem when I use the %quests_player_compass_quest_objectives% placeholder in a scoreboard I have this logo appearing https://imgur.com/a/1sdgR1q

I think it's due to the newline you use

**Comment by PikaMug** [comment]
Correct. For a scoreboard, you'll need to first parse the data somehow.

**Comment by zetlas1610** [comment]
how can i do
