### ISSUE TITLE
Placeholder %quests_player_compass_quest_name%

### ISSUE THREAD

**Issue by Blskk** [PikaMug/PlaceholderExpansion-Quests#19]
#18 
There are still cases where null values are not returned

[delete]in addition：And after completing one quest, if the player has another quest, it will not automatically switch to that quest[/delete]

**Comment by PikaMug** [comment]
Which cases? Need an explanation of how to replicate the issues - or is it only when switching quests?

**Comment by Blskk** [comment]
> 哪些情况？需要解释如何复制问题 - 还是仅在切换任务时？

https://youtu.be/DYfNHZFdj0o
Placeholder use:
%quests_player_compass_quest_name%
%quests_player_compass_quest_objectives%
In this test, only the situation where the placeholder did not return a null value occurred

paper-1.20.1  Quests-5.0.0-rc.4   PlaceholderAPI-2.11.5

**Comment by PikaMug** [comment]
Thank you. Should be fixed in https://github.com/PikaMug/Quests/commit/3413895abf4ec174d4d9c3869a34601874c4a073 so update to https://ci.codemc.io/job/PikaMug/job/Quests/443/
