### ISSUE TITLE
Placeholders dont work everything is setup correctly and no error's in console.

### ISSUE THREAD

**Issue by Jeavess** [PikaMug/PlaceholderExpansion-Quests#3]
only the %quests_player_has_current_quest_<quest>% works

all the other placeholder code's dont work.

please update this or if its a commun issue please let me know what i do wrong.

**Comment by PikaMug** [comment]
Need more information. What are your Quests / PAPI / expansion versions? How are you trying to display the placeholder(s)?

**Comment by PikaMug** [comment]
Closing due to lack of response from OP.
