### ISSUE TITLE
Quest Points top Placeholder

### ISSUE THREAD

**Issue by JessePesse123** [PikaMug/PlaceholderExpansion-Quests#4]
What does your feature do?
A placeholder that outputs the playername of the player with the most questpoints. Or for example Quests_quest_points_top would give you the playername of that place in the top.
How would people use it?
People could implement it in scoreboard, Banner Boards,...

**Comment by PikaMug** [comment]
Thanks for the suggestion. Quests does not currently cache this information and therefore it would be too slow to collect for such a placeholder at this time.
