### ISSUE TITLE
Bug: Placeholder isn't updated when quest changes stage

### ISSUE THREAD

**Issue by Maitlans** [PikaMug/PlaceholderExpansion-Quests#7]
Hi so currently when a quest moves stages the placeholder it seems like it untracks the quest the quest name placeholder goes blank while the objective stays the same so like what currently happens is for example:

What is displayed on the placeholder when you first start the quest:
Quest name: Zombies
Objective: Kill Zombies: 0/5

What you see after finishing that first stage and switching to the next:
Quest name:
Objective: Kill Zombies: 4/5

And it'll just stay like this until you use the compass to refresh and switch back to the same quest and this will happen for every stage.

Thank you.

**Comment by PikaMug** [comment]
This is technically an issue with Quests itself and will be addressed in the next update.
