### ISSUE TITLE
Cannot get %quests_player_current_objectives_[quest]%

### ISSUE THREAD

**Issue by PappoYT** [PikaMug/PlaceholderExpansion-Quests#8]
I'm running:
Quests-4.0.0-rc.3-build-185.jar
Expansion-Quests-1.3.jar
over Paper 1.16.4

I cannot get current Objectives name using %quests_player_current_objectives_%quests_player_current_quest_names%%

**Comment by DeadlykillOfficial** [comment]
You can't have placeholder inside of placeholder
